 version: '2'

 services:
   elastic:
     image: elasticsearch:2.4.0
     volumes:
       - /etc/timezone:/etc/timezone
     command: -Des.network.host=0.0.0.0 -Dhttp.cors.enabled=true -Dhttp.cors.allow-origin=*
     ports:
       - "9200:9200"
       - "9300:9300"


   logstash1:
     environment: 
       - counter_seed=1
       - counter_increment=3
     command: /opt/logstash/bin/logstash agent -f /config-dir/logstash1.conf
     volumes:
       - ${PWD}/logstash-config:/config-dir
       - /etc/timezone:/etc/timezone
     image: vivekjuneja/logstash:6
     depends_on:
       - elastic
       - zookeeper
       - kafka


   logstash2:
     environment: 
       - counter_seed=2
       - counter_increment=3
     command: /opt/logstash/bin/logstash agent -f /config-dir/logstash2.conf
     volumes:
       - ${PWD}/logstash-config:/config-dir
       - /etc/timezone:/etc/timezone
     image: vivekjuneja/logstash:6
     depends_on:
       - elastic
       - zookeeper
       - kafka


   kibana:
     environment: 
       - ELASTICSEARCH_URL=http://elastic:9200
     volumes:
       - /etc/timezone:/etc/timezone
     image: kibana:4.6.3
     ports:
       - "5601:5601"
     depends_on:
       - elastic

   filebeat:
     command: /bin/filebeat -e -v -d "*" -c /etc/filebeat/filebeat.yml
     volumes:
       - ${PWD}/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml
       - /var/log/messages:/var/log/messages
       - /etc/timezone:/etc/timezone
     image: prima/filebeat:latest
     depends_on:
       - kafka

   callee:
     environment: 
       - PORT=8000
       - TIMEINSECONDS=2      
       - ENV=prod
       - PROJECT=microservice
     ports:
       - "8000:8000"
     image: callee:latest
     logging:
       driver: "syslog"
       options:
         syslog-facility: "daemon"
         tag: "docker/{{ (.ExtraAttributes nil).ENV }}/{{ (.ExtraAttributes nil).PROJECT }}"
         env: "ENV,PROJECT"
         labels: "busybox"

   caller:
     environment: 
       - PORT=8001
       - CALLEE_HOSTPORT=callee:8000
       - ENV=prod
       - PROJECT=microservice
     ports:
       - "8001:8001"
     image: caller:latest
     logging:
       driver: "syslog"
       options:
         syslog-facility: "daemon"
         tag: "docker/{{ (.ExtraAttributes nil).ENV }}/{{ (.ExtraAttributes nil).PROJECT }}"
         env: "ENV,PROJECT"
         labels: "busybox"

   zookeeper:
     image: wurstmeister/zookeeper
     ports:
       - "2181:2181"
   kafka:
     build: ./kafka/
     ports:
       - "9092:9092"
     environment:
       KAFKA_ADVERTISED_HOST_NAME: 192.168.99.101
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock


