 version: '2'

 services:
   elastic:
     environment: 
       - LOGSPOUT=ignore
     image: elasticsearch:2.4.0
     command: -Des.network.host=0.0.0.0 -Dhttp.cors.enabled=true -Dhttp.cors.allow-origin=*
     ports:
       - "9200:9200"
       - "9300:9300"


   logstash1:
     environment: 
       - counter_seed=1
       - counter_increment=3
       - LOGSPOUT=ignore
     command: /opt/logstash/bin/logstash agent -f /config-dir/logstash.conf
     volumes:
       - ${PWD}/logstash-config:/config-dir
     image: vivekjuneja/logstash:6
     ports:
       - "5001:5000"
     depends_on:
       - elastic


   logstash2:
     environment: 
       - counter_seed=2
       - counter_increment=3
       - LOGSPOUT=ignore
     command: /opt/logstash/bin/logstash agent -f /config-dir/logstash.conf
     volumes:
       - ${PWD}/logstash-config:/config-dir
     image: vivekjuneja/logstash:6
     ports:
       - "5002:5000"
     depends_on:
       - elastic


   kibana:
     environment: 
       - LOGSPOUT=ignore
       - ELASTICSEARCH_URL=http://elastic:9200
     image: kibana:4.2.2
     ports:
       - "5601:5601"
     depends_on:
       - elastic

   haproxy:
     environment: 
       - LOGSPOUT=ignore
     volumes:
       - ${PWD}/haproxy-config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
     image: haproxy
     ports:
       - "80:80"
     depends_on:
       - logstash1
       - logstash2
